---
name: Object-Simple
version: 0.01_02
author:
  - 'Yuki <kimoto.yuki@gmail.com>'
abstract: Very simple framework for Object Oriented Perl.
license: perl
resources:
  license: ~
requires:
  Object::Simple::Constraint: 0
  Object::Simple::Error: 0
  Scalar::Util: 1.14
  Storable: 0
build_requires:
  Test::More: 0
provides:
  Object::Simple:
    file: lib/Object/Simple.pm
    version: 0.01_02
  Object::Simple::Functions:
    file: lib/Object/Simple.pm
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
