---
name: Object-Simple
version: 2.0803
author:
  - 'Yuki <kimoto.yuki@gmail.com>'
abstract: Simple class builder
license: perl
resources:
  license: ~
requires:
  Scalar::Util: 1.14
build_requires:
  Test::More: 0
provides:
  Object::Simple:
    file: lib/Object/Simple.pm
    version: 2.0803
  Object::Simple::Functions:
    file: lib/Object/Simple.pm
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
