---
name: Object-Simple
version: 2.0018
author:
  - 'Yuki <kimoto.yuki@gmail.com>'
abstract: Light Weight Minimal Object System
license: perl
resources:
  license: ~
requires:
  Scalar::Util: 1.14
build_requires:
  Test::More: 0
provides:
  Object::Simple:
    file: lib/Object/Simple.pm
    version: 2.0018
  Object::Simple::Functions:
    file: lib/Object/Simple.pm
  Object::Simple::MIXINS:
    file: lib/Object/Simple.pm
  Object::Simple::UPPER:
    file: lib/Object/Simple.pm
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
